FROM php:7.4-apache
COPY ./ /var/www/html/
RUN docker-php-ext-install mysqli
RUN apt-get update && apt install -y  \
nano \
&& rm -rf /var/lib/apt/lists/*
RUN apt upgrade
RUN echo  "root:pitevna" | chpasswd
RUN apt-get update -y
RUN apt-get install -y iputils-ping
